/*
 * GPIO_Program.c
 *
 *  Created on: May 6, 2025
 *      Author: Ahmed
 */

#include "GPIO_Interface.h"

/* =============================== */
/*      LOW-LEVEL GPIO CONTROL     */
/* =============================== */

/**
 * @brief Set the mode of a GPIO pin (input, output, AF, analog).
 */
void GPIO_Mode(GPIO_RegDef_t *GPIO, GPIO_Pin_Number_t N, GPIO_Mode_t M)
{
	GPIO->MODER &= ~(0b11 << (2 * N));
	GPIO->MODER |= (M << (2 * N));
}

/**
 * @brief Set output type (push-pull or open-drain).
 */
void GPIO_Output_Type(GPIO_RegDef_t *GPIO, GPIO_Pin_Number_t N, GPIO_Output_Type_t O)
{
	GPIO->OTYPER &= ~(0b1 << N);
	GPIO->OTYPER |= (O << N);
}

/**
 * @brief Set output speed for a GPIO pin.
 */
void GPIO_Speed(GPIO_RegDef_t *GPIO, GPIO_Pin_Number_t N, GPIO_Speed_t S)
{
	GPIO->OSPEEDR &= ~(0b11 << (2 * N));
	GPIO->OSPEEDR |= (S << (2 * N));
}

/**
 * @brief Configure internal pull-up or pull-down resistors.
 */
void GPIO_Pull_Up_Pull_Down(GPIO_RegDef_t *GPIO, GPIO_Pin_Number_t N, GPIO_Pull_Up_Pull_Down_t P)
{
	GPIO->PUPDR &= ~(0b11 << (2 * N));
	GPIO->PUPDR |= (P << (2 * N));
}

/**
 * @brief Read digital input value from GPIO pin.
 */
uint32_t GPIO_Input(GPIO_RegDef_t *GPIO, GPIO_Pin_Number_t N)
{
	return ((GPIO->IDR >> N) & 0b1);
}

/**
 * @brief Write digital output value to GPIO pin.
 */
void GPIO_Output_Data(GPIO_RegDef_t *GPIO, GPIO_Pin_Number_t N, GPIO_Output_Data_t O)
{
	GPIO->ODR &= ~(0b1 << N);
	GPIO->ODR |= (O << N);
}

/**
 * @brief Select alternate function for a GPIO pin.
 */
void GPIO_Alternate_Function(GPIO_RegDef_t *GPIO, GPIO_Pin_Number_t N, GPIO_Alternate_Function_t F)
{
	if (N < 8)
	{
		GPIO->AFRL &= ~(0b1111 << (4 * N));
		GPIO->AFRL |= (F << (4 * N));
	}
	else
	{
		GPIO->AFRH &= ~(0b1111 << (4 * (N - 8)));
		GPIO->AFRH |= (F << (4 * (N - 8)));
	}
}

/* =============================== */
/*     HIGH-LEVEL CONFIG HELPERS   */
/* =============================== */

/**
 * @brief Configures a GPIO pin for PWM output using alternate function mode.
 *
 * 🧠 Core Idea:
 * - This function prepares a GPIO pin to output a PWM signal generated by a timer peripheral.
 * - It configures the pin in **Alternate Function mode**, assigns the appropriate **AF number**,
 *   and sets proper electrical characteristics for stable high-speed signal output.
 *
 * 🛠 What It Does:
 * 1. Sets the pin mode to Alternate Function (`GPIO_ALTERNATE_FUNCTION`).
 * 2. Sets the pin output speed to High (`GPIO_HIGH_SPEED`) for fast PWM switching.
 * 3. Configures output type as Push-Pull (`GPIO_PUSH_PULL`)—standard for most timer outputs.
 * 4. Disables internal pull-up/pull-down resistors to avoid signal distortion.
 * 5. Selects the correct Alternate Function number (AFx) that connects the timer to this pin.
 *
 * 🔧 Recommended Use:
 * - Call this function before enabling the timer and starting PWM.
 * - Useful when working with timers like TIM2, TIM3, etc., and using their PWM output channels.
 *
 * ⚙️ Example:
 *   GPIO_configurePWM(GPIOA, 1, GPIO_AF1); // PA1 = TIM2_CH2 (AF1)
 */
void GPIO_configurePWM(GPIO_RegDef_t *port, uint8_t pin, uint8_t af)
{
	GPIO_Mode(port, pin, GPIO_ALTERNATE_FUNCTION);
	GPIO_Speed(port, pin, GPIO_HIGH_SPEED);
	GPIO_Output_Type(port, pin, GPIO_PUSH_PULL);
	GPIO_Pull_Up_Pull_Down(port, pin, GPIO_NO_PULL_UP_NO_PULL_DOWN);
	GPIO_Alternate_Function(port, pin, af);
}

/**
 * @brief Configures a GPIO pin as an analog input.
 *
 * 🧠 Core Idea:
 * - This function sets the selected pin to analog mode, which is required for ADC operation.
 * - It also disables internal pull-up and pull-down resistors to avoid interference with the analog signal.
 *
 * 🔧 Recommended Use:
 * - Use this function when preparing a GPIO pin to be connected to the ADC peripheral.
 *
 * ⚙️ Example:
 *   GPIO_configureAnalogInput(GPIOA, 5); // Configure PA5 as ADC input (e.g., ADC Channel 5)
 */
void GPIO_configureAnalogInput(GPIO_RegDef_t *port, uint8_t pin)
{
	GPIO_Mode(port, pin, GPIO_ANALOG);
	GPIO_Pull_Up_Pull_Down(port, pin, GPIO_NO_PULL_UP_NO_PULL_DOWN);
}
